version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
    depends_on:
      - prometheus
      - tempo
      - otel-collector

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - '9090'
    ports:
      - 9090:9090

  beyla:
    image: grafana/beyla:latest
    command: ["--config=/etc/beyla/config.yaml"]
    pid: "service:backend"
    privileged: true
    environment:
      - BEYLA_PRINT_TRACES=true
      - BEYLA_OPEN_PORT=8080
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - BEYLA_OTEL_INSECURE_SKIP_VERIFY=true
    volumes:
      - ./beyla/:/etc/beyla/
    depends_on:
      - backend

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    restart: always
    volumes:
      - ./tempo/:/etc/tempo/
      - tempo_data:/tmp/tempo
    # ports:
    #   - "3200:3200"   # tempo
    #   - "9095:9095" # tempo grpc
    #   - "4317:4317"  # otlp grpc
    #   - "4318:4318"  # otlp http

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./otel-collector/:/etc/otel-collector/
    ports:
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "55681:55681" # other receivers
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - tempo
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password

volumes:
  prometheus_data: {}
  tempo_data: {}
  grafana_data: {}
