receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  attributes:
    actions:
      - key: data_source
        value: 'otel-collector'
        action: insert

exporters:
  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [otlp]
