global:
  scrape_interval: 5s
  external_labels:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:9999']
