apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-o11y
  labels:
    app: learning-o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-o11y
  template:
    metadata:
      labels:
        app: learning-o11y
    spec:
      containers:
        - name: learning-o11y
          image: garyhu1030/learning-o11y:v0.0.2
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 9090
              name: metrics
