apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-server-service
  labels:
    app: opentelemetry-demo-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: server
      protocol: TCP
    - name: metrics
      port: 9999
      targetPort: metrics
      protocol: TCP
  selector:
    app: opentelemetry-demo-server
