apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-demo-server-metrics
  labels:
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: observability-demo-server
  endpoints:
    - interval: 15s
      targetPort: metrics
      path: /metrics
