receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  attributes:
    actions:
      - key: data_source
        value: 'otel-collector'
        action: insert

  batch:
    send_batch_size: 8192
    timeout: 200ms

  filter:
    spans:
      exclude:
        match_type: regexp
        span_names:
          - ^/opentelemetry.*

  memory_limiter:
    check_interval: 10s
    limit_mib: 4000
    spike_limit_mib: 500

  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 30

exporters:
  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:9464'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        [attributes, batch, filter, memory_limiter, probabilistic_sampler]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [attributes]
      exporters: [prometheus]
