name: Create and publish Docker images

on:
  push:
    tags:
      - v*

env:
  SERVER_IMAGE_NAME: garyhu1030/opentelemetry-demo-server
  TELLME_APP_IMAGE_NAME: garyhu1030/opentelemetry-demo-tellme-app

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - { name: 'server', path: 'server' }
          - { name: 'tellme-app', path: 'tellme-app' }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env[matrix.app.name | upper | replace('-', '_') | append('_IMAGE_NAME') ] }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.app.path }}
          file: ${{ matrix.app.path }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
